const main=document.querySelector('#main');
const homeMarkup=main.innerHTML;
const dialog=document.querySelector('#story-dialog');
const menuButton=document.querySelector('.menu-toggle');
const nav=document.querySelector('#primary-nav');
let voices=[],cards=[],geography=[],activeTheme='全部',activeCity='全部城市',selectedCity='广州',rainEnabled=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const themes=['在雨中工作','屋檐与照顾','与潮湿共处','声音与风景','成长与归属'];
const themeDescriptions={'全部':'每个人记住的雨都不一样。','在雨中工作':'出行、收入、计划和责任，被一场雨改变。','屋檐与照顾':'地铁口、小店和临时遮雨处，容纳短暂的照顾。','与潮湿共处':'花、纸张、琴键和住房里的水汽，进入日常选择。','声音与风景':'从声音、倒影、植物到建筑，留意雨落下的地方。','成长与归属':'雨连接童年、家庭、长大，以及离开广东后的记忆。'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>/^https:\/\//.test(s)?esc(s):'#';
menuButton.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')!=='true';menuButton.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});
function closeMenu(){nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});

function startRain(){
  const canvas=document.querySelector('#rain');if(!canvas)return;
  const ctx=canvas.getContext('2d');let w,h,last=performance.now();
  const drops=Array.from({length:90},()=>({x:Math.random(),y:Math.random(),speed:.17+Math.random()*.3,length:10+Math.random()*24}));
  function resize(){w=canvas.width=canvas.clientWidth;h=canvas.height=canvas.clientHeight}resize();window.addEventListener('resize',resize);
  const button=document.querySelector('.rain-toggle');function update(){button.textContent='雨幕 · '+(rainEnabled?'开':'关');button.setAttribute('aria-pressed',String(rainEnabled))}update();button.onclick=()=>{rainEnabled=!rainEnabled;update()};
  function frame(now){if(!canvas.isConnected){window.removeEventListener('resize',resize);return}const dt=Math.min((now-last)/1000,.04);last=now;ctx.clearRect(0,0,w,h);if(rainEnabled&&!document.hidden){ctx.strokeStyle='rgba(205,235,255,.32)';ctx.lineWidth=.8;for(const d of drops){d.y+=d.speed*dt;if(d.y>1.08){d.y=-.1;d.x=Math.random()}ctx.beginPath();ctx.moveTo(d.x*w,d.y*h);ctx.lineTo(d.x*w-4,d.y*h+d.length);ctx.stroke()}}requestAnimationFrame(frame)}requestAnimationFrame(frame);
}

function voiceCard(v,featured=false){return `<button class="voice-card ${featured?'featured-card':''}" data-story="${esc(v.id)}" aria-label="阅读${esc(v.name)}的故事：${esc(v.title)}"><span class="card-meta"><span>${esc(v.theme)}</span><span>${String(v.order).padStart(2,'0')}</span></span><h3>${esc(v.title)}</h3><p class="story-hook">${esc(v.hook)}</p><span class="card-person"><span><strong>${esc(v.name)}</strong><span>${esc(v.role)} · ${esc(v.city)}</span></span><span class="read-label">阅读故事</span></span></button>`}
function bindStoryCards(){document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>openStory(b.dataset.story))}
function home(){
  main.innerHTML=homeMarkup+`<section class="home-voices"><div class="section"><div class="section-heading"><div><p class="eyebrow">SIX VOICES TO BEGIN WITH</p><h2>同一场雨，<br>不同的生活。</h2></div><div><p>从听雨到赶路，从照顾他人到想家。<br>先读六段记忆，再走进更多人的雨季。</p><a class="button light" href="#/voices">浏览全部45个声音</a></div></div><div class="voice-grid">${voices.slice(0,6).map(v=>voiceCard(v,true)).join('')}</div><p class="editor-note">页面结构原型 · 声音条目为占位内容，待真实访谈替换与核实</p></div></section><section class="section home-map"><div class="map-teaser-image"><img src="assets/city-08.jpg" alt="围屋与水塘的地方生活景观" loading="lazy"><span>RAIN MAP / 梅州</span></div><div><p class="eyebrow">A GEOGRAPHY OF EVERYDAY LIFE</p><h2>从一座城市，<br>走进一种生活。</h2><p>骑楼留出遮雨的路，晒场等待晴天，茶罐守住干燥。选一座城市，翻开它与雨的联系。</p><a href="#/map" class="button">探索广东21城</a></div></section>`;
  startRain();bindStoryCards();
}

function pageHead(english,title,description,num){return `<section class="page-head"><div class="breadcrumbs"><a href="#/">首页</a><span>/</span><span>${english}</span></div><div class="page-head-grid"><div><p class="eyebrow">${num} / THE MONSOON ARCHIVE</p><h1>${english}</h1></div><div><h2>${title}</h2><p>${description}</p></div></div></section>`}
function onward(route,label,text){return `<section class="onward section"><div><p class="eyebrow">KEEP EXPLORING</p><h2>${text}</h2></div><a class="button" href="#/${route}">${label}</a></section>`}
function voicesPage(){
  const cities=[...new Set(voices.map(v=>v.city))];
  main.innerHTML=pageHead('Rain Voices','雨落下来，生活有不同的回应。','这一版以45段占位故事测试浏览、筛选与完整阅读体验。正式内容将在真实访谈完成后替换与核实。','02')+`<section class="section voices-collection"><div class="collection-top"><span class="small-heading">按一条线索，走进故事</span><label class="city-filter">城市 <select id="voice-city"><option>全部城市</option>${cities.map(c=>`<option ${c===activeCity?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><div class="theme-filters" aria-label="故事主题">${['全部',...themes].map(t=>`<button class="theme-button ${t===activeTheme?'selected':''}" aria-pressed="${t===activeTheme}" data-theme="${esc(t)}">${t}<span>${t==='全部'?voices.length:voices.filter(v=>v.theme===t).length}</span></button>`).join('')}</div><div class="results-line"><p id="theme-description">${themeDescriptions[activeTheme]}</p><span id="result-count" aria-live="polite"></span></div><div class="voice-grid" id="voices-grid"></div><p class="editor-note">网站原型内容 · 待真实访谈完成后替换、核实并编辑。</p></section>`+onward('map','打开 Rain Map','再看看，雨落在什么地方。');
  document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{activeTheme=b.dataset.theme;document.querySelectorAll('[data-theme]').forEach(x=>{x.classList.toggle('selected',x.dataset.theme===activeTheme);x.setAttribute('aria-pressed',String(x.dataset.theme===activeTheme))});document.querySelector('#theme-description').textContent=themeDescriptions[activeTheme];filterVoices()});
  document.querySelector('#voice-city').onchange=e=>{activeCity=e.target.value;filterVoices()};filterVoices();
}
function filterVoices(){const filtered=voices.filter(v=>(activeTheme==='全部'||v.theme===activeTheme)&&(activeCity==='全部城市'||v.city===activeCity));document.querySelector('#result-count').textContent=`${filtered.length} / 45 个声音`;document.querySelector('#voices-grid').innerHTML=filtered.length?filtered.map(v=>voiceCard(v)).join(''):`<div class="empty-result"><h3>这条线索下还没有故事</h3><p>试试另一个城市，或回到全部声音。</p><button class="button" id="reset-filter">查看全部声音</button></div>`;const reset=document.querySelector('#reset-filter');if(reset)reset.onclick=()=>{activeTheme='全部';activeCity='全部城市';voicesPage()};bindStoryCards()}
function openStory(id){
  const index=voices.findIndex(v=>v.id===id);if(index<0)return;const v=voices[index];
  dialog.innerHTML=`<div class="dialog-top"><span>RAIN VOICES / ${String(v.order).padStart(2,'0')}</span><button class="dialog-close" aria-label="关闭故事">关闭 ×</button></div><article class="story-detail"><p class="eyebrow">${esc(v.theme)}</p><h2 id="dialog-title">${esc(v.title)}</h2><div class="detail-person"><strong>${esc(v.name)}</strong><span>${esc(v.role)} · ${esc(v.city)}</span></div><div class="story-body">${v.body.split('\n').filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}</div><div class="detail-tags">${v.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><p class="editor-note">原型占位内容 · 待真实访谈替换与核实。</p><div class="story-controls"><button data-prev ${index===0?'disabled':''}>上一篇</button><span>${index+1} / ${voices.length}</span><button data-next ${index===voices.length-1?'disabled':''}>下一篇</button></div></article>`;
  dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.querySelector('[data-prev]').onclick=()=>openStory(voices[index-1].id);dialog.querySelector('[data-next]').onclick=()=>openStory(voices[index+1].id);if(!dialog.open)dialog.showModal();dialog.scrollTop=0;dialog.querySelector('.dialog-close').focus({preventScroll:true});
}
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});

function mapSvg(){return `<svg class="guangdong-map" viewBox="0 0 1000 800" aria-labelledby="map-title map-description"><title id="map-title">广东21城雨季文化地图</title><desc id="map-description">选择一座城市，查看对应文化卡牌。也可用地图下方的城市按钮选择。箭头为春末夏初水汽与冷空气的概念示意，不是实时天气。</desc><defs><marker id="wind-head" markerWidth="7" markerHeight="7" refX="5" refY="3.5" orient="auto"><path d="M0 0L6 3.5L0 7" fill="none" stroke="#8ec9e5" stroke-width="1.2"/></marker></defs><g class="map-graticule" aria-hidden="true"><path d="M0 180H1000M0 350H1000M0 520H1000M0 690H1000M190 0V800M410 0V800M630 0V800M850 0V800"/><text x="890" y="682">21°N</text><text x="890" y="512">23°N</text></g><g class="city-regions">${geography.map(g=>`<path class="city-region ${g.city===selectedCity?'selected':''}" data-city="${g.city}" d="${g.path}" role="button" tabindex="0" aria-label="选择${g.city}" aria-pressed="${g.city===selectedCity}"><title>${g.city}</title></path>`).join('')}</g><g class="city-labels" aria-hidden="true">${geography.map(g=>`<text x="${g.x}" y="${g.y+5}" class="city-label ${g.city===selectedCity?'selected':''}" data-label="${g.city}">${g.city}</text>`).join('')}</g><g class="climate-flow" aria-hidden="true"><path d="M325 40 Q345 65 350 95" marker-end="url(#wind-head)"/><text x="310" y="24">南下的冷空气</text><path d="M415 729 Q454 645 478 510" marker-end="url(#wind-head)"/><path d="M560 740 Q599 668 622 584" marker-end="url(#wind-head)"/><text x="605" y="683">暖湿气流 / 南海夏季风</text><text class="sea-label" x="670" y="746">南　海</text></g><g class="compass" aria-hidden="true"><path d="M80 90V48M74 56L80 46L86 56"/><text x="75" y="36">N</text></g></svg>`}
function mapPage(){
  main.innerHTML=pageHead('Rain Map','一场雨，落在21座城市。','从地图进入广东的地方生活。点击城市，翻开一张卡牌：看一处建筑、一种食物，或一件与湿度相处的日常物品。','01')+`<section class="map-experience"><div class="map-workspace"><div class="map-surface"><div class="map-toolbar"><span>广东 / GUANGDONG</span><span>选择城市，翻开地方记忆</span></div>${mapSvg()}<div class="map-legend"><span><i></i> 选中的城市</span><span>气流为定性示意，非实时天气</span></div></div><aside id="city-panel" aria-label="城市文化卡牌"></aside></div><div class="city-directory"><p>选择一座城市</p><div>${cards.map(c=>`<button class="city-button ${c.city===selectedCity?'selected':''}" data-pick-city="${c.city}" aria-pressed="${c.city===selectedCity}">${c.city}</button>`).join('')}</div></div></section><section class="section climate-story"><div><p class="eyebrow">WHY THE RAIN COMES</p><h2>雨，从海洋来到日常。</h2><p>春末夏初，暖湿空气不断向华南输送水汽。与南下冷空气相遇、配合有利的环流条件时，降雨可能变得集中而强烈。广东的“龙舟水”，也与端午前后的生活记忆相连。</p><div class="climate-steps"><div><span>01</span><h3>海洋提供水汽</h3><p>来自热带海洋的暖湿气流持续向华南输送。</p></div><div><span>02</span><h3>冷暖空气相遇</h3><p>水汽、上升运动与环流条件共同影响降雨。</p></div><div><span>03</span><h3>生活回应天气</h3><p>遮雨、排水、晾晒与储存，成为地方日常的一部分。</p></div></div><p class="source-line">气候说明：<a href="https://swj.gz.gov.cn/swyw/rdxw/content/post_10817534.html" target="_blank" rel="noopener noreferrer">广州市水务局 · 龙舟水的成因与时段</a>。地图边界：<a href="https://datav.aliyun.com/portal/school/atlas/area_selector" target="_blank" rel="noopener noreferrer">阿里云 DataV 地理数据</a>；仅供本项目文化浏览。</p></div></section>`+onward('voices','阅读 Rain Voices','地方有形状，记忆有声音。');
  document.querySelectorAll('[data-city]').forEach(p=>{p.onclick=()=>selectCity(p.dataset.city);p.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectCity(p.dataset.city)}}});document.querySelectorAll('[data-pick-city]').forEach(b=>b.onclick=()=>selectCity(b.dataset.pickCity));renderCity();
}
function selectCity(city){selectedCity=city;document.querySelectorAll('[data-city]').forEach(el=>{el.classList.toggle('selected',el.dataset.city===city);el.setAttribute('aria-pressed',String(el.dataset.city===city))});document.querySelectorAll('[data-label]').forEach(el=>el.classList.toggle('selected',el.dataset.label===city));document.querySelectorAll('[data-pick-city]').forEach(el=>{el.classList.toggle('selected',el.dataset.pickCity===city);el.setAttribute('aria-pressed',String(el.dataset.pickCity===city))});renderCity();if(matchMedia('(max-width: 900px)').matches)document.querySelector('#city-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}
function renderCity(){
  const c=cards.find(c=>c.city===selectedCity)||cards[0];const n=cards.indexOf(c)+1;
  const captions={'广州':'骑楼建筑外观','深圳':'公园中的水面与绿地','珠海':'萝兜粽','汕头':'小公园街区','佛山':'龙舟竞渡','韶关':'围屋建筑外观','河源':'米粉晾晒','梅州':'围屋、禾坪与水塘','惠州':'梅菜成品','汕尾':'渔港中的停泊船只','东莞':'草席编织','中山':'腊味晾晒','江门':'新会柑皮晾晒','阳江':'漆皮箱','湛江':'鱼干晾晒','茂名':'荔枝采收与分拣','肇庆':'村落与环绕水体','清远':'红茶干茶','潮州':'工夫茶席','揭阳':'塑料拖鞋','云浮':'凉果晾晒'};
  document.querySelector('#city-panel').innerHTML=`<div class="city-panel-heading"><span>FIELD NOTES / ${String(n).padStart(2,'0')}</span><span>${c.category}</span></div><div class="flip-card city-reveal"><div class="flip-inner"><article class="flip-front"><div class="city-photo"><img src="${c.photo}" alt="${esc(captions[c.city])}" width="600" height="470"><span>${esc(c.city)}<small>GUANGDONG</small></span></div><div class="city-front-copy"><p>${esc(c.subject)}</p><h2>${esc(c.title)}</h2><button class="button flip-button" data-flip="true" aria-label="翻面阅读${esc(c.city)}的故事">翻面阅读</button></div></article><article class="flip-back" aria-hidden="true" inert><p class="eyebrow">${esc(c.city)} / ${esc(c.category)}</p><h2>${esc(c.title)}</h2><p class="city-body">${esc(c.body)}</p><span class="caption">图片：${esc(captions[c.city])}</span><button class="button" data-flip="false">回到照片</button></article></div></div><div class="city-card-bottom"><p aria-live="polite">正在阅读：${c.city} · ${c.subject}</p><details><summary>这张卡牌的文字资料</summary>${c.sources.map(s=>`<a href="${safeUrl(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`).join('')}</details></div>`;
  document.querySelectorAll('[data-flip]').forEach(b=>b.onclick=()=>{const flip=b.dataset.flip==='true';document.querySelector('.flip-card').classList.toggle('flipped',flip);const front=document.querySelector('.flip-front'),back=document.querySelector('.flip-back');front.inert=flip;back.inert=!flip;front.setAttribute('aria-hidden',String(flip));back.setAttribute('aria-hidden',String(!flip));(flip?back:front).querySelector('button').focus({preventScroll:true})});
}

function placeholderBox(label,number='01'){return `<div class="photo-placeholder"><span>${number} / IMAGE SPACE</span><div class="image-slot-mark" aria-hidden="true">＋</div><p>${label}</p></div>`}
function pendingPage(type){
  if(type==='stories')main.innerHTML=pageHead('Rain Stories','留住雨里的一个片刻。','用摄影观察广东的雨季：等待的人、继续工作的街道，以及晴天到来之前的生活。','03')+`<section class="section pending-section"><p class="status-label">内容整理中 / PHOTOGRAPHY IN PROGRESS</p><div class="pending-intro"><h2>照片还在路上，<br>观察的位置已经留好。</h2><p>这里将是一组照片与简短观察。每一张图片，都留下一件容易被雨声盖过的小事。</p></div><div class="photo-slots"><div>${placeholderBox('待补：屋檐下等待的人','01')}<h3>等待</h3><p>一张雨中停留或避雨的照片，配一句对人物与空间的观察。</p></div><div>${placeholderBox('待补：街道、地铁口或市场','02')}<h3>穿行</h3><p>一张城市仍在运转的照片，记录人怎样继续赶路或工作。</p></div><div>${placeholderBox('待补：晾衣、修伞或校园生活','03')}<h3>与雨相处</h3><p>一张具体的日常细节，呈现天气如何进入生活习惯。</p></div></div><div class="materials-needed"><h3>这一部分还需要</h3><p>选定的照片、每张一句观察、拍摄地点与已知时间，以及图片来源和署名。可继续补入等雨的人、修伞的人、外卖员、菜市场与校园等主题。</p></div></section>`+onward('voices','阅读已经收录的故事','先听听，照片之外的声音。');
  else if(type==='objects')main.innerHTML=pageHead('Rain Objects','湿度，留在物品的细节里。','从保存一张纸、一片茶，到保持一间屋子的干燥，物品记录着人们如何适应广东的天气。','04')+`<section class="section pending-section"><p class="status-label">内容整理中 / OBJECTS IN PROGRESS</p><div class="pending-intro"><h2>从一件物品，<br>读懂一种相处方式。</h2><p>物件档案将补充实物照片与使用故事。以下是原始提纲中的候选主题，具体内容仍在整理。</p></div><div class="object-slots">${[['除湿机','收集空气中的水分'],['防潮箱','为需要干燥的物品留出空间'],['拖鞋','雨天里的材质与穿着选择'],['凉茶','地方生活中的饮食习惯'],['骑楼','连续屋檐下的城市空间']].map(([name,text],i)=>`<article>${placeholderBox('待补：'+name+'照片',String(i+1).padStart(2,'0'))}<h3>${name}</h3><p>${text}</p></article>`).join('')}</div><div class="materials-needed"><h3>每个物件还需要</h3><p>一张清楚的实物或使用场景照片、名称、简短说明、它与雨季或湿度的具体联系，以及相关资料来源。地方历史与起源将在资料确认后补入。</p></div></section>`+onward('map','从地图认识地方物件','有些线索，已经留在21城里。');
  else main.innerHTML=pageHead('Physics Meets Humanity','雨为什么落下，落下之后又怎样？','以科学理解天气，以人的经验理解生活。这是 Monsoon Archive 连接两种观察方式的起点。','05')+`<section class="section reflection-section"><p class="status-label">个人篇章整理中 / A REFLECTION IN PROGRESS</p><div class="reflection-line"><span>01 / PHYSICS</span><h2>从空气中的水汽，<br>看到一场雨的形成。</h2><p>地图里的暖湿气流与冷空气，为观察广东雨季提供了一个科学入口。</p><a class="text-link" href="#/map">查看 Rain Map 的气候说明</a></div><div class="reflection-line"><span>02 / HUMANITY</span><h2>从人的记忆，<br>看到雨留下的痕迹。</h2><p>一份工作、一把借出的伞、一件被潮气改变的物品，让天气拥有了生活中的尺度。</p><a class="text-link" href="#/voices">走进 Rain Voices</a></div><div class="author-space"><div>${placeholderBox('可补：个人观察照片、田野笔记或项目手稿')}</div><div><p class="eyebrow">A PERSONAL NOTE</p><h2>我为什么开始<br>记录广东的雨？</h2><p>这里为项目作者的个人文字预留。</p><ul><li>你与广东、雨季或物理学的关系。</li><li>让你开始这个项目的一个具体经历。</li><li>整理故事与图像后，哪些想法发生了变化。</li><li>你希望访客带走的一个问题。</li></ul></div></div></section>`+onward('','返回首页','换一个入口，继续看雨。');
}

function renderRoute(){
  const hash=location.hash;if(hash&& !hash.startsWith('#/'))return;
  const route=hash.replace(/^#\//,'').split('/')[0]||'home';const valid=['home','map','voices','stories','objects','reflection'];const page=valid.includes(route)?route:'home';
  closeMenu();if(dialog.open)dialog.close();document.body.dataset.page=page;
  document.querySelectorAll('[data-route]').forEach(a=>{const active=a.dataset.route===page;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
  if(page==='home')home();else if(page==='map')mapPage();else if(page==='voices')voicesPage();else pendingPage(page);
  const titles={home:'与雨共同生活',map:'Rain Map · 广东21城',voices:'Rain Voices · 45个声音',stories:'Rain Stories · 摄影档案',objects:'Rain Objects · 雨季物件',reflection:'Physics Meets Humanity'};
  document.title=titles[page]+' | Monsoon Archive';window.scrollTo({top:0,behavior:'instant'});
  main.setAttribute('tabindex','-1');main.focus({preventScroll:true});
}
Promise.all(['voices','cards','map'].map(name=>fetch('assets/'+name+'.json').then(r=>{if(!r.ok)throw new Error(name);return r.json()}))).then(([v,c,g])=>{voices=v;cards=c;geography=g;window.addEventListener('hashchange',renderRoute);renderRoute()}).catch(()=>{main.insertAdjacentHTML('afterbegin','<div class="load-error" role="alert">档案暂时没有加载成功。<button onclick="location.reload()">重新加载</button></div>');startRain()});
